 steps:
 # build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/healthcare-predictions/cms-scrape:$COMMIT_SHA', '.']
   dir: cms-scrape
 # push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/healthcare-predictions/cms-scrape:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/cloud-builders/gcloud'
   args:
   - 'run'
   - 'deploy'
   - 'cms-scrape'
   - '--image'
   - 'gcr.io/healthcare-predictions/cms-scrape:$COMMIT_SHA'
   - '--region'
   - 'us-central1'
   - '--platform'
   - 'managed'
 images:
 - 'gcr.io/healthcare-predictions/cms-scrape:$COMMIT_SHA'