# Google CLI and Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.0
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    
    working_directory: ~/cms-kubernetes
    
    steps:
      - run: |
          echo {$GCLOUD_SERVICE_KEY} | gcloud auth activate-service-account {$GCLOUD_EMAIL} --key-file=-
          gcloud --quiet config set project {$GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone {$GOOGLE_COMPUTE_ZONE}

      - checkout

      # Download and cache dependencies
      #- restore_cache:
          #keys:
            #- v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            #- v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
          
      - run:
          name: set credentials
          command: 
            export GOOGLE_APPLICATION_CREDENTIALS=$GCLOUD_SERVICE_KEY

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test
      # run lints!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
