# CircleCI 2.1, Google SDK, and Orbs for CI/CD
#
# Check https://circleci.com/orbs/registry/?query=gcp for more details
#
version: 2.1
orbs:
  node: circleci/node@1.0.1
  gcp-gke: circleci/gcp-gke@1.0.4
  gcr: circleci/gcp-gcr@0.7.1
jobs:
  build:
    description: Build and push front-end image to GCR
    machine: true
    working_directory: ~/cms-kubernetes
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          image: healthcare-predictions-app
          path: ~/cms-kubernetes/app/frontend
          tag: "v.1.1" # Change version number when updating 
      - gcr/push-image:
          image: healthcare-predictions-app
          tag: "v.1.1" # Change version number when updating 
  deploy:
    description: Deploy API and front-end to GKE
    machine: true
    steps:
      - gcp-gke/install
      - gcp-gke/update-kubeconfig-with-credentials:
          cluster: healthcare-predictions-dev
          gcloud-service-key: GCLOUD_SERVICE_KEY
          gcloud-compute-zone: GOOGLE_COMPUTE_ZONE
          google-project-id: GOOGLE_PROJECT_ID
          perform-login: true
      - gcp-gke/rollout-image:
          cluster: healthcare-predictions-dev
          container: healthcare-predictions-api
          deployment: heatlhcare-api
          image: healthcare-predictions-api
          namespace: healthcare-app
          tag: v.1.1 # Change version number when updating 
      - gcp-gke/rollout-image:
          cluster: healthcare-predictions-dev
          container: healthcare-predictions-frontend
          deployment: healthcare-frontend
          image: healthcare-predictions-app
          namespace: healthcare-app
          tag: v.1.1 # Change version number when updating
workflows:
  version: 2
  dev_test_build_deploy:
    jobs:
      - build:
      - deploy: