# Google CLI and Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
orbs:
    gcp-cli: circleci/gcp-cli@1.8.4
description: |
  Install gcloud CLI and initialize to connect to Google Cloud
executor: <<parameters.executor>>
parameters:
  executor:
    default: default
    description: |
      Executor to use for this job. Defaults to this orb's default executor.
    type: executor
  gcloud-service-key:
    default: GCLOUD_SERVICE_KEY
    description: The gcloud service key
    type: env_var_name
  google-compute-zone:
    default: GOOGLE_COMPUTE_ZONE
    description: The Google compute zone to connect with via the gcloud CLI
    type: env_var_name
  google-project-id:
    default: GOOGLE_PROJECT_ID
    description: The Google project ID to connect with via the gcloud CLI
    type: env_var_name
steps:
  - install
  - initialize:
      gcloud-service-key: <<parameters.gcloud-service-key>>
      google-compute-zone: <<parameters.google-compute-zone>>
      google-project-id: <<parameters.google-project-id>>
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/cms-kubernetes

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test
      # run lints!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
