# CircleCI 2.0 and Google SDK configuration file
#
# Check https://circleci.com/docs/2.0/google-auth/ for more details
#
version: 2.1
orbs:
  node: circleci/node@1.0.1
  gcp-gke: circleci/gcp-gke@1.0.4
  gcr: circleci/gcp-gcr@0.7.1
jobs:
  build:
    description: Build and push API image to GCR
    machine: true
    working_directory: ~/cms-kubernetes
    steps:
      - checkout
      - run:
          name: Copy Service Key to API Directory
          command: |
            echo $GCLOUD_SERVICE_KEY > .app/api/healthcare-predictions-85c2b5783a5e.json
      - gcr/gcr-auth
      - gcr/build-image:
          image: healthcare-predictions-api
          path: ~/cms-kubernetes/app/api
          tag: "v.1.1"
      - gcr/push-image:
          image: healthcare-predictions-api
          tag: "v.1.1"
