apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: healthcare-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare-api
  template:
    metadata:
      labels:
        app: healthcare-api
        track: stable
        version: 1.0.0
    spec:
      containers:
      - name: healthcare-predictions-api
        image: gcr.io/healthcare-predictions/healthcare-predictions-api:v.1
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 80
        resources:
          requests: # minimum resources required
            cpu: 250m
            memory: 64Mi
          limits: # maximum resources allocated
            cpu: 500m
            memory: 256Mi
        #livenessProbe:
            #httpGet:
              #path: /healthz
              #port: 80
            #initialDelaySeconds: 5
            #periodSeconds: 15
            #timeoutSeconds: 5
        #readinessProbe:
            #httpGet:
              #path: /readiness
              #port: 80
            #initialDelaySeconds: 5
            #timeoutSeconds: 1